### ISSUE TITLE
? bug in searching for trials with publications

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#513] opened 2016-10-19 15:11 UTC
when searching for trials with publications, trials appear that don't have publications but do have research summaries. potentially the research summaries are being counted as publications?

could we change the search criteria so research summaries are not counted as publications?

thanks!

**Comment by benmeg** [comment] 2016-10-20 01:05
Duplicate of #492

**Closed by benmeg** 2016-10-20 01:05 UTC
Labels: bug
