### ISSUE TITLE
Cochrane Risk of Bias summary not linked to publication

### ISSUE THREAD

**Issue by benmeg** [opentrials/opentrials#489] opened 2016-10-13 00:31 UTC
On this trial: [The Efficacy and Safety of Risperidone in the Treatment of Adolescents With Schizophrenia](http://explorer.opentrials.net/trials/c98ff25c-1b98-4bd9-a249-7943a4738aa5)

At the bottom of the page, there are two entries for `Methodological rigour` - they link to:

1) [Atypical antipsychotics for psychosis in adolescents (Review)](http://onlinelibrary.wiley.com/doi/10.1002/14651858.CD009582/full)
2) [Risperidone dose for schizophrenia (Review)](http://onlinelibrary.wiley.com/doi/10.1002/14651858.CD007474.pub2/full)

However, it appears that only '1' includes the related publication ([Haas, 2009](https://www.ncbi.nlm.nih.gov/pubmed/19182179)) in its Risk of Bias summary.

To verify, see Risk of Bias tables (links to full papers below):

1) [Figure 2 on page 20 (numbered 16)](https://drive.google.com/open?id=0B7spV2gFO4aveHZIQXh5T1BxM1E) - publication is 4th down
2) [Figure 2 on page 19 (numbered 14)](https://drive.google.com/open?id=0B7spV2gFO4avUVNfaUQxSmpPc1E) - publication is NOT listed

So the question is: where is the second paragraph coming from?

**Comment by georgiana-b** [comment] 2016-10-14 08:36
This is the data that was extracted from the second trial XML (see `doi_id`). In the `refs` fields (which stands for "references") the first reference is to the same publication. The confusion probably comes from how they display the data inside XMLs in HTML. 

```json
[
  {
    "id": "2db70a088a3711e6acf2e4b3181a2c8c",
    "meta_created": "2016-10-04 13:33:47.618485",
    "study_type": "PUB",
    "file_name": "Risperidone dose for schizophrenia [v6.26-for discussion with CLive].rm5",
    "meta_source": "http://datastore.opentrials.net/uploads/d7823d80-6f81-11e6-87af-931e370d0cf8/cochrane_schizophrenia_reviews.zip",
    "robs": "[{\"result\": \"YES\", \"rob_id\": \"QIT-01\", \"group_id\": \"\", \"modified\": \"2014-06-09 10:35:09 +0100\", \"rob_name\": \"Random sequence generation (selection bias)\", \"study_id\": \"STD-Haas-2009\", \"group_name\": \"\", \"rob_description\": \"Selection bias (biased allocation to interventions) due to inadequate generation of a randomised sequence\", \"result_description\": \"Randomised - using a computer-generated schedule.\"}, {\"result\": \"UNKNOWN\", \"rob_id\": \"QIT-02\", \"group_id\": \"\", \"modified\": \"2014-06-09 10:35:28 +0100\", \"rob_name\": \"Allocation concealment (selection bias)\", \"study_id\": \"STD-Haas-2009\", \"group_name\": \"\", \"rob_description\": \"Selection bias (biased allocation to interventions) due to inadequate concealment of allocations prior to assignment\", \"result_description\": \"No description.\"}, {\"result\": \"UNKNOWN\", \"rob_id\": \"QIT-03\", \"group_id\": \"QIG-03.02\", \"modified\": \"2014-06-09 10:36:58 +0100\", \"rob_name\": \"Blinding (performance bias and detection bias)\", \"study_id\": \"STD-Haas-2009\", \"group_name\": \"All outcomes\", \"rob_description\": \"Performance bias or detection bias due to knowledge of the allocated interventions after assignment\", \"result_description\": \"Double-blind - no further details.\"}, {\"result\": \"YES\", \"rob_id\": \"QIT-04\", \"group_id\": \"QIG-04.01\", \"modified\": \"2014-06-09 10:37:58 +0100\", \"rob_name\": \"Incomplete outcome data (attrition bias)\", \"study_id\": \"STD-Haas-2009\", \"group_name\": \"All outcomes\", \"rob_description\": \"Attrition bias due to amount, nature or handling of incomplete outcome data\", \"result_description\": \"Description of terminated reasons, ITT analysis.\"}, {\"result\": \"NO\", \"rob_id\": \"QIT-05\", \"group_id\": \"\", \"modified\": \"2014-06-09 10:39:19 +0100\", \"rob_name\": \"Selective reporting (reporting bias)\", \"study_id\": \"STD-Haas-2009\", \"group_name\": \"\", \"rob_description\": \"Reporting bias due to selective outcome reporting\", \"result_description\": \"EKG, blood chemistry test. No data.\"}, {\"result\": \"NO\", \"rob_id\": \"QIT-06\", \"group_id\": \"\", \"modified\": \"2014-06-09 10:41:21 +0100\", \"rob_name\": \"Other bias\", \"study_id\": \"STD-Haas-2009\", \"group_name\": \"\", \"rob_description\": \"Bias due to problems not covered elsewhere in the table\", \"result_description\": \"Funded by Johnson & Johnson Pharmaceutical Research & Development\"}]",
    "study_id": "STD-Haas-2009",
    "meta_id": "2db70e5e8a3711e6acf2e4b3181a2c8c",
    "refs": "[{\"no\": \"2\", \"pg\": \"158-64\", \"vl\": \"194\", \"type\": \"JOURNAL_ARTICLE\", \"year\": \"2009\", \"title\": \"Efficacy, safety and tolerability of two dosing regimens in adolescent schizophrenia: double-blind study\", \"source\": \"The British journal of psychiatry : the journal of mental science\", \"authors\": \"Haas M, Eerdekens M, Kushner S, Singer J, Augustyns I, Quiroz J, et al\", \"country\": \"\", \"identifiers\": [{\"type\": \"PUBMED\", \"value\": \"19182179\"}]}]",
    "doi_id": "10.1002/14651858.CD007474.pub2",
    "meta_updated": "2016-10-04 13:33:47.618485"
  }
]
```

So this is not a bug.
This is not the case here but sometimes the Cochrane reviews have `NCT` ids as a references in which case they are linked directly to the trial so correlating only through publications may not reveal the connection.

**Comment by georgiana-b** [comment] 2016-10-14 16:46
The issue was a mismatch between the data in the published review and the more updated XML that hasn't been published yet. Closing this in favor of #494.

**Closed by georgiana-b** 2016-10-14 16:46 UTC
Labels: bug
