### ISSUE TITLE
Fix deduplication of trials with bad titles

### ISSUE THREAD

**Issue by jessflem** [opentrials/opentrials#310] opened 2016-08-16 08:46 UTC
http://explorer.opentrials.net/trials/5fbbb609-7c96-4b6d-a956-9d498089a8ee

this is a whole bunch of trials linking through the scientific title [Trial of device that is not approved or cleared by the U.S. FDA] which ct.gov use when:

"This trial has been identified as being associated with a clinical device that has not been approved or cleared by the US Food and Drug Administration. Under the terms of US Public Law 110-85, Title VIII, Section 801, the details of this study are not available to the public."

not sure if you would class it as a bug - but definitely not one trial, potentially need to prevent matching on this title.

---

```
[Trial of device that is not approved or cleared by the U.S. FDA]
See Detailed Description
Principal Investigator
```

**Comment by roll** [comment] 2016-08-25 17:03
Moving it to `in development` because this bug also caused by dedup error which I'm fixing now.

**Comment by roll** [comment] 2016-08-31 11:06
FIXED

**Closed by roll** 2016-08-31 11:06 UTC
Labels: 4. Ready for Review, bug, Processors
