### ISSUE TITLE
Lots of data info missing in UI from nct

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#127] opened 2016-05-16 16:40 UTC
Not sure where the issue is, and the issue could be deeper than just orgs and persons.

- Trial UI: http://explorer.opentrials.net/trials/e568f975-5692-45f7-b965-7fc2bc01a4b7
- Trial API: http://api.opentrials.net/v1/trials/e568f975-5692-45f7-b965-7fc2bc01a4b7

Organisations and persons are empty. But the sources for this trial are:

- https://www.clinicaltrials.gov/ct2/show/NCT02391870?lup_e=02%2F04%2F2016&lup_s=01%2F01%2F2001&rank=21730&resultsxml=true
- http://apps.who.int/trialsearch/Trial3.aspx?trialid=NCT02391870

Both records have *lots* of info on organisations and persons associated with the trial, including person role (principal investigator)

**Comment by pwalsh** [comment] 2016-05-16 16:40
cc @roll

**Comment by vitorbaptista** [comment] 2016-05-16 17:33
Changing tags and assigning this to @roll, as the API and Explorer are correctly displaying the data that they have. The issue is either that this data isn't being collected, or that it isn't being processed correctly.

**Comment by pwalsh** [comment] 2016-05-18 07:24
Another example, showing lots of missing data:

Trial page: http://explorer.opentrials.net/trials/1a1a8b77-196a-43b5-82ad-546fa3a8b0ac
Source data: http://apps.who.int/trialsearch/Trial3.aspx?trialid=DRKS00007960

**Comment by roll** [comment] 2016-05-27 10:51
MERGED
https://github.com/opentrials/opentrials/issues/182

**Closed by roll** 2016-05-27 10:51 UTC
Labels: bug, Collectors, data cleaning, Processors
