### ISSUE TITLE
ValidationError on some compound names

### ISSUE THREAD

**Issue by tstoeger** [opentrials/opentrials#559] opened 2016-11-10 04:48 UTC
Some names / substrings lead to ValidationErrors, when searching trials through bravado and OPENTRIALS_API_SPEC = 'http://api.opentrials.net/v1/swagger.yaml'

There is no reported error, when searching these names through the search function of the open trials webpage.

e.g.:
- ((1R,2R,3aS,9aS)-2-hydroxy-1-((3S)-3-hydroxyoctyl)-2,3,3a,4,9,9a-hexahydro-1H-cylopent(b)naphthalen-5-yl)oxy)acetate 
- (+) or (-)-N-Methyl-gamma-(4-(trifluoromethyl)phenoxy)benzenepropanamine

![validationerror](https://cloud.githubusercontent.com/assets/7517390/20164862/d6a91d2e-a6cd-11e6-9414-4c7e5ab42cec.png)

**Comment by vitorbaptista** [comment] 2016-11-10 09:48
@tstoeger The problem is that the `q` parameter uses ElasticSearch's Query String syntax, which has some specific meanings for things like parenthesi (see https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-query-string-query.html#query-string-syntax). If your query contains those characters (as it does), you'll need to escape them. We have a method to escape elaticsearch queries at https://github.com/opentrials/opentrials/blob/master/helpers/escape-elastic-search.js which you can reuse. Unfortunately that's in JavaScript, but should be easy to convert to Python.

I'm closing this issue now, but feel free to add more comments here or open other issues if you face other problems.

**Closed by vitorbaptista** 2016-11-10 09:48 UTC
Labels: API
