### ISSUE TITLE
Refactor processors tests to use a real database

### ISSUE THREAD

**Issue by georgiana-b** [opentrials/opentrials#525] opened 2016-10-25 10:19 UTC
All tests for writers should use a real database similar to [the one used in `TestDocumentWriter`](https://github.com/opentrials/processors/blob/917a231e5b6e55c59418ad254102d78a63449cb2/tests/processors/base/writers/test_document.py#L140-L162).

**Comment by vitorbaptista** [comment] 2016-10-25 10:21
Duplicate of #526

**Closed by vitorbaptista** 2016-10-25 10:21 UTC
Labels: Processors
